services:
  nginx:
    image: ghcr.io/michlip-eu/vysum.to/frontend:proxy
    ports:
      - '82:80'
  frontend:
    deploy:
      replicas: 2
    restart: always
    image: ghcr.io/michlip-eu/vysum.to/frontend:latest
  backend:
    deploy:
      replicas: 2
    restart: always
    image: ghcr.io/michlip-eu/vysum.to/backend:latest
    environment:
      - DB_HOST=5.249.164.28
      - DB_RESOLVE=false
      - DB_USER=vysum
      - DB_DB=vysum
      - DB_PASSWORD=ubyJAMGA5vG1ad6ybYqZivq8iromo6UnZ2pwFK8nAQQiAJKE53
      - JWT_SECRET=JWT secret fo secure communication between server and client (frontend and backend)
    volumes:
      - storage:/app/image
  watchtower:
    image: containrrr/watchtower
    volumes:
      - $HOME/.docker/config.json/:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
      --cleanup
      --rolling-restart

volumes:
  storage:
