name: Build & Deploy to GHCR

on:
  push:
    branches:
      - main
permissions: write-all

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:frontend
          cache-from: type=gha
          cache-to: type=gha,mode=max

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:backend
          cache-from: type=gha
          cache-to: type=gha,mode=max

  proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./proxy
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:proxy
          cache-from: type=gha
          cache-to: type=gha,mode=max
